name: Release packages

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        ubuntu-version: [24.04]
        arch: [amd64]
    runs-on: "${{ format('ubuntu-{0}{1}', matrix.ubuntu-version, matrix.arch == 'arm64' && '-arm' || '') }}"
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Build renode
        run: |
          mkdir output
          docker build -o ./output .
        env:
          DOCKER_BUILDKIT: '1'
      - name: Release the build packages
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: ./output/packages/*
